### ISSUE TITLE
Problems reading or writing to card.

### ISSUE THREAD

**Issue by WilliamGladwin** [sarakusha/novastar#602]
- **I'm submitting a ...**
  [**x**] question about how to use this project

- **Summary**
I am wondering if you could provide any support with an issue I'm currently facing. I have been able to successfully find the sending card and start a session over that port, however, when trying to read or write I receive no response back and a timeout occurs. 
`const err = new TimeoutError_1.
                            ^
TimeoutError: No response was received for the 
    at Timeout.rejectTimeout (C:\ .....
    at listOnTimeout (node:internal/timers:559:
    at processTimers (node:internal/timers:502:
  req: Request {
    head: [Getter/Setter],
    ack: [Getter/Setter],
    serno: [Getter/Setter],
    source: [Getter/Setter],
    destination: [Getter/Setter],
    deviceType: [Getter/Setter],
    port: [Getter/Setter],
    rcvIndex: [Getter/Setter],
    io: [Getter/Setter],
    address: [Getter/Setter],
    length: [Getter/Setter],
    data: Buffer(1) [Uint8Array] [ 255 ],
    crc: [Getter/Setter],
    tag: undefined,
    broadcast: undefined,
    originalLength: 1,
    timeout: 10000
  },
  tag: undefined
}`

- **Other information** 
Version: 2.0.0-alpha.7
Code being used:
`const [port] = await findSendingCards();
  console.log(port);
  const session = await serial.open({
      path:port.path,
      baudRate:115200,
  });
  console.log(session);
  const readReq = new Request(1);
  readReq.deviceType = DeviceType.ReceivingCard;
  readReq.address = 0x02000001// or 0x00000001;
  readReq.port = 0;
  readReq.timeout = 10000;
  const { data: [value] } = await session.connection.send(readReq);
  console.log(`Brightness on the first receiving card connected to 0 port is ${value}`);
  // Close all serial sessions
  serial.release();`

**Comment by sarakusha** [comment]
I have tested the following code and it works.

```ts
import { DeviceType, Request } from '@novastar/codec';
import serial, { findSendingCards } from '@novastar/serial';

describe('novastar', () => {
  test('serial', async () => {
    const [port] = await findSendingCards();
    console.log({ port });
    const session = await serial.open({
      path: port.path,
      baudRate: 115200,
    });
    try {
      const readReq = new Request(1);
      readReq.deviceType = DeviceType.ReceivingCard;
      readReq.address = 0x02000001;
      readReq.port = 0;
      const { data: [value] } = await session.connection.send(readReq);
      console.log({ value });
// Close all serial sessions
      serial.release();
    } catch (err) {
      console.error(err);
    }
  });
});

```

**Comment by sarakusha** [comment]
The sending card must be connected to the receiving card. All brightness settings are stored on the receiving card.

**Comment by sarakusha** [comment]
In this example, the model ID of the sending card is read. The receiving card is not used.

```ts
  test('modelId', async () => {
    const [port] = await findSendingCards();
    console.log({ port });
    const session = await serial.open({
      path: port.path,
      baudRate: 115200,
    });
    try {
      const readReq = new Request(2);
      readReq.deviceType = DeviceType.SendingCard;
      readReq.address = 2;
      const { data } = await session.connection.send(readReq);
      console.log('modelId', data.readUInt16LE());
// Close all serial sessions
      serial.release();
    } catch (err) {
      console.error(err);
    }
  });

```

**Comment by WilliamGladwin** [comment]
I've tested out both your examples and unfortunately still receive no response, it may be the controller I'm using, I will be testing on a different one when I get my hands on it.
But thank you for the quick reply!

**Comment by WilliamGladwin** [comment]
The only other question I might ask is about the actual hardware configuration you have setup? Could you explain how you have everything connected?
Thank you!

**Comment by sarakusha** [comment]
I used the devices MCTRL300 connected via USB and MCTRL660 PRO connected via Ethernet. The search for devices connected via usb goes by the pair VID/PID. I don't have all the variety of devices so not all USB devices can be detected automatically. Also note that not all devices use 115200 speed. On the other hand, if the device can be connected via Ethernet, then it must work via @novastar/net. It is also important to understand that all network connections are opened in exclusive mode. The device does not support multiple connections.
In your case, I would recommend running the official [NovaLCT](https://oss.novastar.tech/NovaLCT%20V5.4.5.zip) app and making sure everything works.

**Comment by sarakusha** [comment]
I forgot to mention that if the device supports both USB and Ethernet interfaces, then you need to configure it and select the main interface.

**Comment by WilliamGladwin** [comment]
Okay thankyou, I've been testing on a MCTRL600 and just got my hands on a MCTRL300. I also have just received a device that can be connected via ethernet, so I will be testing the @novastar/net in hopes that works.
Thank you for you responses!

**Comment by WilliamGladwin** [comment]
just as an update, I have been able to get it all working using the MCTRL300, thanks for you support!
