### ISSUE TITLE
Cannot find module '@novastar/screen' or its corresponding type declarations.

### ISSUE THREAD

**Issue by evilexecutable** [sarakusha/novastar#611]
- **I'm submitting a ...**
  [* ] question about how to use this project

- **Summary**
Cannot find module '@novastar/screen' or its corresponding type declarations.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. 
 
Unable to import @novastar/screen - All other modules work fine, and I can read data from the receiver card with the following code:

```
import { DeviceType } from '@novastar/codec';
import { Request } from '@novastar/codec';
import serial, { findSendingCards } from '@novastar/serial';

const main = async () => {
    const [port] = await findSendingCards();
    const session = await serial.open({
        path: port.path,
        baudRate: 115200,
    });
    const readReq = new Request(1);
    readReq.deviceType = DeviceType.ReceivingCard;
    readReq.address = 0x02000001;
    readReq.port = 0;
    //const brightness = ScreenConfigurator
    const { data: [value] } = await session.connection.send(readReq);
    console.log({ value });
}

main();
```

When trying to import ScreenConfigurator so that I can read system brightness with
`import ScreenConfigurator from '@novastar/screen';`
I get the above error.

**Comment by sarakusha** [comment]
I have updated the packages, try now.
Successfully published:
 - @novastar/codec@2.0.0-alpha.9
 - @novastar/native@2.0.0-alpha.9
 - @novastar/net@2.0.0-alpha.9
 - @novastar/screen@2.0.0-alpha.9
 - @novastar/serial@2.0.0-alpha.9

**Comment by evilexecutable** [comment]
As easy as that. Thanks @sarakusha.
